# coding: utf-8

"""
    Apache Spark History Server REST API

    REST API for the Apache Spark History Server, providing access to application history, jobs, stages, executors, storage, SQL, streaming, and environment information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from spark_history_mcp.api_client.models.executor_metrics_distributions_peak_memory_metrics import ExecutorMetricsDistributionsPeakMemoryMetrics
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ExecutorMetricsDistributions(BaseModel):
    """
    Quantile distributions of executor metrics.
    """ # noqa: E501
    quantiles: Optional[List[Union[StrictFloat, StrictInt]]] = None
    task_time: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="taskTime")
    failed_tasks: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="failedTasks")
    succeeded_tasks: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="succeededTasks")
    killed_tasks: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="killedTasks")
    input_bytes: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="inputBytes")
    input_records: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="inputRecords")
    output_bytes: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="outputBytes")
    output_records: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="outputRecords")
    shuffle_read: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="shuffleRead")
    shuffle_read_records: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="shuffleReadRecords")
    shuffle_write: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="shuffleWrite")
    shuffle_write_records: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="shuffleWriteRecords")
    memory_bytes_spilled: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="memoryBytesSpilled")
    disk_bytes_spilled: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="diskBytesSpilled")
    peak_memory_metrics: Optional[ExecutorMetricsDistributionsPeakMemoryMetrics] = Field(default=None, alias="peakMemoryMetrics")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["quantiles", "taskTime", "failedTasks", "succeededTasks", "killedTasks", "inputBytes", "inputRecords", "outputBytes", "outputRecords", "shuffleRead", "shuffleReadRecords", "shuffleWrite", "shuffleWriteRecords", "memoryBytesSpilled", "diskBytesSpilled", "peakMemoryMetrics"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExecutorMetricsDistributions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of peak_memory_metrics
        if self.peak_memory_metrics:
            _dict['peakMemoryMetrics'] = self.peak_memory_metrics.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExecutorMetricsDistributions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "quantiles": obj.get("quantiles"),
            "taskTime": obj.get("taskTime"),
            "failedTasks": obj.get("failedTasks"),
            "succeededTasks": obj.get("succeededTasks"),
            "killedTasks": obj.get("killedTasks"),
            "inputBytes": obj.get("inputBytes"),
            "inputRecords": obj.get("inputRecords"),
            "outputBytes": obj.get("outputBytes"),
            "outputRecords": obj.get("outputRecords"),
            "shuffleRead": obj.get("shuffleRead"),
            "shuffleReadRecords": obj.get("shuffleReadRecords"),
            "shuffleWrite": obj.get("shuffleWrite"),
            "shuffleWriteRecords": obj.get("shuffleWriteRecords"),
            "memoryBytesSpilled": obj.get("memoryBytesSpilled"),
            "diskBytesSpilled": obj.get("diskBytesSpilled"),
            "peakMemoryMetrics": ExecutorMetricsDistributionsPeakMemoryMetrics.from_dict(obj["peakMemoryMetrics"]) if obj.get("peakMemoryMetrics") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


