# coding: utf-8

"""
    Apache Spark History Server REST API

    REST API for the Apache Spark History Server, providing access to application history, jobs, stages, executors, storage, SQL, streaming, and environment information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Job(BaseModel):
    """
    Job
    """ # noqa: E501
    job_id: Optional[StrictInt] = Field(default=None, alias="jobId")
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    submission_time: Optional[StrictStr] = Field(default=None, alias="submissionTime")
    completion_time: Optional[StrictStr] = Field(default=None, alias="completionTime")
    stage_ids: Optional[List[StrictInt]] = Field(default=None, alias="stageIds")
    job_group: Optional[StrictStr] = Field(default=None, alias="jobGroup")
    job_tags: Optional[List[StrictStr]] = Field(default=None, alias="jobTags")
    status: Optional[StrictStr] = None
    num_tasks: Optional[StrictInt] = Field(default=None, alias="numTasks")
    num_active_tasks: Optional[StrictInt] = Field(default=None, alias="numActiveTasks")
    num_completed_tasks: Optional[StrictInt] = Field(default=None, alias="numCompletedTasks")
    num_skipped_tasks: Optional[StrictInt] = Field(default=None, alias="numSkippedTasks")
    num_failed_tasks: Optional[StrictInt] = Field(default=None, alias="numFailedTasks")
    num_killed_tasks: Optional[StrictInt] = Field(default=None, alias="numKilledTasks")
    num_completed_indices: Optional[StrictInt] = Field(default=None, alias="numCompletedIndices")
    num_active_stages: Optional[StrictInt] = Field(default=None, alias="numActiveStages")
    num_completed_stages: Optional[StrictInt] = Field(default=None, alias="numCompletedStages")
    num_skipped_stages: Optional[StrictInt] = Field(default=None, alias="numSkippedStages")
    num_failed_stages: Optional[StrictInt] = Field(default=None, alias="numFailedStages")
    killed_tasks_summary: Optional[Dict[str, StrictInt]] = Field(default=None, alias="killedTasksSummary")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["jobId", "name", "description", "submissionTime", "completionTime", "stageIds", "jobGroup", "jobTags", "status", "numTasks", "numActiveTasks", "numCompletedTasks", "numSkippedTasks", "numFailedTasks", "numKilledTasks", "numCompletedIndices", "numActiveStages", "numCompletedStages", "numSkippedStages", "numFailedStages", "killedTasksSummary"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['RUNNING', 'SUCCEEDED', 'FAILED', 'UNKNOWN']):
            raise ValueError("must be one of enum values ('RUNNING', 'SUCCEEDED', 'FAILED', 'UNKNOWN')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Job from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Job from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "jobId": obj.get("jobId"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "submissionTime": obj.get("submissionTime"),
            "completionTime": obj.get("completionTime"),
            "stageIds": obj.get("stageIds"),
            "jobGroup": obj.get("jobGroup"),
            "jobTags": obj.get("jobTags"),
            "status": obj.get("status"),
            "numTasks": obj.get("numTasks"),
            "numActiveTasks": obj.get("numActiveTasks"),
            "numCompletedTasks": obj.get("numCompletedTasks"),
            "numSkippedTasks": obj.get("numSkippedTasks"),
            "numFailedTasks": obj.get("numFailedTasks"),
            "numKilledTasks": obj.get("numKilledTasks"),
            "numCompletedIndices": obj.get("numCompletedIndices"),
            "numActiveStages": obj.get("numActiveStages"),
            "numCompletedStages": obj.get("numCompletedStages"),
            "numSkippedStages": obj.get("numSkippedStages"),
            "numFailedStages": obj.get("numFailedStages"),
            "killedTasksSummary": obj.get("killedTasksSummary")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


