# coding: utf-8

"""
    Apache Spark History Server REST API

    REST API for the Apache Spark History Server, providing access to application history, jobs, stages, executors, storage, SQL, streaming, and environment information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PeakMemoryMetrics(BaseModel):
    """
    PeakMemoryMetrics
    """ # noqa: E501
    jvm_heap_memory: Optional[StrictInt] = Field(default=None, alias="JVMHeapMemory")
    jvm_off_heap_memory: Optional[StrictInt] = Field(default=None, alias="JVMOffHeapMemory")
    on_heap_execution_memory: Optional[StrictInt] = Field(default=None, alias="OnHeapExecutionMemory")
    off_heap_execution_memory: Optional[StrictInt] = Field(default=None, alias="OffHeapExecutionMemory")
    on_heap_storage_memory: Optional[StrictInt] = Field(default=None, alias="OnHeapStorageMemory")
    off_heap_storage_memory: Optional[StrictInt] = Field(default=None, alias="OffHeapStorageMemory")
    on_heap_unified_memory: Optional[StrictInt] = Field(default=None, alias="OnHeapUnifiedMemory")
    off_heap_unified_memory: Optional[StrictInt] = Field(default=None, alias="OffHeapUnifiedMemory")
    direct_pool_memory: Optional[StrictInt] = Field(default=None, alias="DirectPoolMemory")
    mapped_pool_memory: Optional[StrictInt] = Field(default=None, alias="MappedPoolMemory")
    process_tree_jvmv_memory: Optional[StrictInt] = Field(default=None, alias="ProcessTreeJVMVMemory")
    process_tree_jvmrss_memory: Optional[StrictInt] = Field(default=None, alias="ProcessTreeJVMRSSMemory")
    process_tree_python_v_memory: Optional[StrictInt] = Field(default=None, alias="ProcessTreePythonVMemory")
    process_tree_python_rss_memory: Optional[StrictInt] = Field(default=None, alias="ProcessTreePythonRSSMemory")
    process_tree_other_v_memory: Optional[StrictInt] = Field(default=None, alias="ProcessTreeOtherVMemory")
    process_tree_other_rss_memory: Optional[StrictInt] = Field(default=None, alias="ProcessTreeOtherRSSMemory")
    minor_gc_count: Optional[StrictInt] = Field(default=None, alias="MinorGCCount")
    minor_gc_time: Optional[StrictInt] = Field(default=None, alias="MinorGCTime")
    major_gc_count: Optional[StrictInt] = Field(default=None, alias="MajorGCCount")
    major_gc_time: Optional[StrictInt] = Field(default=None, alias="MajorGCTime")
    total_gc_time: Optional[StrictInt] = Field(default=None, alias="TotalGCTime")
    concurrent_gc_count: Optional[StrictInt] = Field(default=None, alias="ConcurrentGCCount")
    concurrent_gc_time: Optional[StrictInt] = Field(default=None, alias="ConcurrentGCTime")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["JVMHeapMemory", "JVMOffHeapMemory", "OnHeapExecutionMemory", "OffHeapExecutionMemory", "OnHeapStorageMemory", "OffHeapStorageMemory", "OnHeapUnifiedMemory", "OffHeapUnifiedMemory", "DirectPoolMemory", "MappedPoolMemory", "ProcessTreeJVMVMemory", "ProcessTreeJVMRSSMemory", "ProcessTreePythonVMemory", "ProcessTreePythonRSSMemory", "ProcessTreeOtherVMemory", "ProcessTreeOtherRSSMemory", "MinorGCCount", "MinorGCTime", "MajorGCCount", "MajorGCTime", "TotalGCTime", "ConcurrentGCCount", "ConcurrentGCTime"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PeakMemoryMetrics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PeakMemoryMetrics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "JVMHeapMemory": obj.get("JVMHeapMemory"),
            "JVMOffHeapMemory": obj.get("JVMOffHeapMemory"),
            "OnHeapExecutionMemory": obj.get("OnHeapExecutionMemory"),
            "OffHeapExecutionMemory": obj.get("OffHeapExecutionMemory"),
            "OnHeapStorageMemory": obj.get("OnHeapStorageMemory"),
            "OffHeapStorageMemory": obj.get("OffHeapStorageMemory"),
            "OnHeapUnifiedMemory": obj.get("OnHeapUnifiedMemory"),
            "OffHeapUnifiedMemory": obj.get("OffHeapUnifiedMemory"),
            "DirectPoolMemory": obj.get("DirectPoolMemory"),
            "MappedPoolMemory": obj.get("MappedPoolMemory"),
            "ProcessTreeJVMVMemory": obj.get("ProcessTreeJVMVMemory"),
            "ProcessTreeJVMRSSMemory": obj.get("ProcessTreeJVMRSSMemory"),
            "ProcessTreePythonVMemory": obj.get("ProcessTreePythonVMemory"),
            "ProcessTreePythonRSSMemory": obj.get("ProcessTreePythonRSSMemory"),
            "ProcessTreeOtherVMemory": obj.get("ProcessTreeOtherVMemory"),
            "ProcessTreeOtherRSSMemory": obj.get("ProcessTreeOtherRSSMemory"),
            "MinorGCCount": obj.get("MinorGCCount"),
            "MinorGCTime": obj.get("MinorGCTime"),
            "MajorGCCount": obj.get("MajorGCCount"),
            "MajorGCTime": obj.get("MajorGCTime"),
            "TotalGCTime": obj.get("TotalGCTime"),
            "ConcurrentGCCount": obj.get("ConcurrentGCCount"),
            "ConcurrentGCTime": obj.get("ConcurrentGCTime")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


