# coding: utf-8

"""
    Apache Spark History Server REST API

    REST API for the Apache Spark History Server, providing access to application history, jobs, stages, executors, storage, SQL, streaming, and environment information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from spark_history_mcp.api_client.models.rdd_storage_info_data_distribution_inner import RDDStorageInfoDataDistributionInner
from spark_history_mcp.api_client.models.rdd_storage_info_partitions_inner import RDDStorageInfoPartitionsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RDDStorageInfo(BaseModel):
    """
    RDDStorageInfo
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    num_partitions: Optional[StrictInt] = Field(default=None, alias="numPartitions")
    num_cached_partitions: Optional[StrictInt] = Field(default=None, alias="numCachedPartitions")
    storage_level: Optional[StrictStr] = Field(default=None, alias="storageLevel")
    memory_used: Optional[StrictInt] = Field(default=None, alias="memoryUsed")
    disk_used: Optional[StrictInt] = Field(default=None, alias="diskUsed")
    data_distribution: Optional[List[RDDStorageInfoDataDistributionInner]] = Field(default=None, alias="dataDistribution")
    partitions: Optional[List[RDDStorageInfoPartitionsInner]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "name", "numPartitions", "numCachedPartitions", "storageLevel", "memoryUsed", "diskUsed", "dataDistribution", "partitions"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RDDStorageInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data_distribution (list)
        _items = []
        if self.data_distribution:
            for _item_data_distribution in self.data_distribution:
                if _item_data_distribution:
                    _items.append(_item_data_distribution.to_dict())
            _dict['dataDistribution'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in partitions (list)
        _items = []
        if self.partitions:
            for _item_partitions in self.partitions:
                if _item_partitions:
                    _items.append(_item_partitions.to_dict())
            _dict['partitions'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RDDStorageInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "numPartitions": obj.get("numPartitions"),
            "numCachedPartitions": obj.get("numCachedPartitions"),
            "storageLevel": obj.get("storageLevel"),
            "memoryUsed": obj.get("memoryUsed"),
            "diskUsed": obj.get("diskUsed"),
            "dataDistribution": [RDDStorageInfoDataDistributionInner.from_dict(_item) for _item in obj["dataDistribution"]] if obj.get("dataDistribution") is not None else None,
            "partitions": [RDDStorageInfoPartitionsInner.from_dict(_item) for _item in obj["partitions"]] if obj.get("partitions") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


