# coding: utf-8

"""
    Apache Spark History Server REST API

    REST API for the Apache Spark History Server, providing access to application history, jobs, stages, executors, storage, SQL, streaming, and environment information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from spark_history_mcp.api_client.models.resource_profile_executor_resources_value import ResourceProfileExecutorResourcesValue
from spark_history_mcp.api_client.models.resource_profile_task_resources_value import ResourceProfileTaskResourcesValue
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResourceProfile(BaseModel):
    """
    ResourceProfile
    """ # noqa: E501
    id: Optional[StrictInt] = None
    executor_resources: Optional[Dict[str, ResourceProfileExecutorResourcesValue]] = Field(default=None, alias="executorResources")
    task_resources: Optional[Dict[str, ResourceProfileTaskResourcesValue]] = Field(default=None, alias="taskResources")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "executorResources", "taskResources"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourceProfile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in executor_resources (dict)
        _field_dict = {}
        if self.executor_resources:
            for _key_executor_resources in self.executor_resources:
                if self.executor_resources[_key_executor_resources]:
                    _field_dict[_key_executor_resources] = self.executor_resources[_key_executor_resources].to_dict()
            _dict['executorResources'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in task_resources (dict)
        _field_dict = {}
        if self.task_resources:
            for _key_task_resources in self.task_resources:
                if self.task_resources[_key_task_resources]:
                    _field_dict[_key_task_resources] = self.task_resources[_key_task_resources].to_dict()
            _dict['taskResources'] = _field_dict
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourceProfile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "executorResources": dict(
                (_k, ResourceProfileExecutorResourcesValue.from_dict(_v))
                for _k, _v in obj["executorResources"].items()
            )
            if obj.get("executorResources") is not None
            else None,
            "taskResources": dict(
                (_k, ResourceProfileTaskResourcesValue.from_dict(_v))
                for _k, _v in obj["taskResources"].items()
            )
            if obj.get("taskResources") is not None
            else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


