# coding: utf-8

"""
    Apache Spark History Server REST API

    REST API for the Apache Spark History Server, providing access to application history, jobs, stages, executors, storage, SQL, streaming, and environment information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from spark_history_mcp.api_client.models.sql_plan_edge import SQLPlanEdge
from spark_history_mcp.api_client.models.sql_plan_node import SQLPlanNode
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SQLExecution(BaseModel):
    """
    SQLExecution
    """ # noqa: E501
    id: Optional[StrictInt] = None
    status: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    plan_description: Optional[StrictStr] = Field(default=None, alias="planDescription")
    submission_time: Optional[StrictStr] = Field(default=None, alias="submissionTime")
    duration: Optional[StrictInt] = None
    running_job_ids: Optional[List[StrictInt]] = Field(default=None, alias="runningJobIds")
    success_job_ids: Optional[List[StrictInt]] = Field(default=None, alias="successJobIds")
    failed_job_ids: Optional[List[StrictInt]] = Field(default=None, alias="failedJobIds")
    nodes: Optional[List[SQLPlanNode]] = None
    edges: Optional[List[SQLPlanEdge]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "status", "description", "planDescription", "submissionTime", "duration", "runningJobIds", "successJobIds", "failedJobIds", "nodes", "edges"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['COMPLETED', 'RUNNING', 'FAILED']):
            raise ValueError("must be one of enum values ('COMPLETED', 'RUNNING', 'FAILED')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SQLExecution from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in nodes (list)
        _items = []
        if self.nodes:
            for _item_nodes in self.nodes:
                if _item_nodes:
                    _items.append(_item_nodes.to_dict())
            _dict['nodes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in edges (list)
        _items = []
        if self.edges:
            for _item_edges in self.edges:
                if _item_edges:
                    _items.append(_item_edges.to_dict())
            _dict['edges'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SQLExecution from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "status": obj.get("status"),
            "description": obj.get("description"),
            "planDescription": obj.get("planDescription"),
            "submissionTime": obj.get("submissionTime"),
            "duration": obj.get("duration"),
            "runningJobIds": obj.get("runningJobIds"),
            "successJobIds": obj.get("successJobIds"),
            "failedJobIds": obj.get("failedJobIds"),
            "nodes": [SQLPlanNode.from_dict(_item) for _item in obj["nodes"]] if obj.get("nodes") is not None else None,
            "edges": [SQLPlanEdge.from_dict(_item) for _item in obj["edges"]] if obj.get("edges") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


