# coding: utf-8

"""
    Apache Spark History Server REST API

    REST API for the Apache Spark History Server, providing access to application history, jobs, stages, executors, storage, SQL, streaming, and environment information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from spark_history_mcp.api_client.models.accumulator_update import AccumulatorUpdate
from spark_history_mcp.api_client.models.executor_metrics_distributions import ExecutorMetricsDistributions
from spark_history_mcp.api_client.models.executor_stage_summary import ExecutorStageSummary
from spark_history_mcp.api_client.models.peak_memory_metrics import PeakMemoryMetrics
from spark_history_mcp.api_client.models.speculation_stage_summary import SpeculationStageSummary
from spark_history_mcp.api_client.models.task import Task
from spark_history_mcp.api_client.models.task_metrics_summary import TaskMetricsSummary
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StageData(BaseModel):
    """
    StageData
    """ # noqa: E501
    status: Optional[StrictStr] = None
    stage_id: Optional[StrictInt] = Field(default=None, alias="stageId")
    attempt_id: Optional[StrictInt] = Field(default=None, alias="attemptId")
    num_tasks: Optional[StrictInt] = Field(default=None, alias="numTasks")
    num_active_tasks: Optional[StrictInt] = Field(default=None, alias="numActiveTasks")
    num_complete_tasks: Optional[StrictInt] = Field(default=None, alias="numCompleteTasks")
    num_failed_tasks: Optional[StrictInt] = Field(default=None, alias="numFailedTasks")
    num_killed_tasks: Optional[StrictInt] = Field(default=None, alias="numKilledTasks")
    num_completed_indices: Optional[StrictInt] = Field(default=None, alias="numCompletedIndices")
    submission_time: Optional[StrictStr] = Field(default=None, alias="submissionTime")
    first_task_launched_time: Optional[StrictStr] = Field(default=None, alias="firstTaskLaunchedTime")
    completion_time: Optional[StrictStr] = Field(default=None, alias="completionTime")
    failure_reason: Optional[StrictStr] = Field(default=None, alias="failureReason")
    executor_deserialize_time: Optional[StrictInt] = Field(default=None, alias="executorDeserializeTime")
    executor_deserialize_cpu_time: Optional[StrictInt] = Field(default=None, alias="executorDeserializeCpuTime")
    executor_run_time: Optional[StrictInt] = Field(default=None, alias="executorRunTime")
    executor_cpu_time: Optional[StrictInt] = Field(default=None, alias="executorCpuTime")
    result_size: Optional[StrictInt] = Field(default=None, alias="resultSize")
    jvm_gc_time: Optional[StrictInt] = Field(default=None, alias="jvmGcTime")
    result_serialization_time: Optional[StrictInt] = Field(default=None, alias="resultSerializationTime")
    memory_bytes_spilled: Optional[StrictInt] = Field(default=None, alias="memoryBytesSpilled")
    disk_bytes_spilled: Optional[StrictInt] = Field(default=None, alias="diskBytesSpilled")
    peak_execution_memory: Optional[StrictInt] = Field(default=None, alias="peakExecutionMemory")
    input_bytes: Optional[StrictInt] = Field(default=None, alias="inputBytes")
    input_records: Optional[StrictInt] = Field(default=None, alias="inputRecords")
    output_bytes: Optional[StrictInt] = Field(default=None, alias="outputBytes")
    output_records: Optional[StrictInt] = Field(default=None, alias="outputRecords")
    shuffle_remote_blocks_fetched: Optional[StrictInt] = Field(default=None, alias="shuffleRemoteBlocksFetched")
    shuffle_local_blocks_fetched: Optional[StrictInt] = Field(default=None, alias="shuffleLocalBlocksFetched")
    shuffle_fetch_wait_time: Optional[StrictInt] = Field(default=None, alias="shuffleFetchWaitTime")
    shuffle_remote_bytes_read: Optional[StrictInt] = Field(default=None, alias="shuffleRemoteBytesRead")
    shuffle_remote_bytes_read_to_disk: Optional[StrictInt] = Field(default=None, alias="shuffleRemoteBytesReadToDisk")
    shuffle_local_bytes_read: Optional[StrictInt] = Field(default=None, alias="shuffleLocalBytesRead")
    shuffle_read_bytes: Optional[StrictInt] = Field(default=None, alias="shuffleReadBytes")
    shuffle_read_records: Optional[StrictInt] = Field(default=None, alias="shuffleReadRecords")
    shuffle_corrupt_merged_block_chunks: Optional[StrictInt] = Field(default=None, alias="shuffleCorruptMergedBlockChunks")
    shuffle_merged_fetch_fallback_count: Optional[StrictInt] = Field(default=None, alias="shuffleMergedFetchFallbackCount")
    shuffle_merged_remote_blocks_fetched: Optional[StrictInt] = Field(default=None, alias="shuffleMergedRemoteBlocksFetched")
    shuffle_merged_local_blocks_fetched: Optional[StrictInt] = Field(default=None, alias="shuffleMergedLocalBlocksFetched")
    shuffle_merged_remote_chunks_fetched: Optional[StrictInt] = Field(default=None, alias="shuffleMergedRemoteChunksFetched")
    shuffle_merged_local_chunks_fetched: Optional[StrictInt] = Field(default=None, alias="shuffleMergedLocalChunksFetched")
    shuffle_merged_remote_bytes_read: Optional[StrictInt] = Field(default=None, alias="shuffleMergedRemoteBytesRead")
    shuffle_merged_local_bytes_read: Optional[StrictInt] = Field(default=None, alias="shuffleMergedLocalBytesRead")
    shuffle_remote_reqs_duration: Optional[StrictInt] = Field(default=None, alias="shuffleRemoteReqsDuration")
    shuffle_merged_remote_reqs_duration: Optional[StrictInt] = Field(default=None, alias="shuffleMergedRemoteReqsDuration")
    shuffle_write_bytes: Optional[StrictInt] = Field(default=None, alias="shuffleWriteBytes")
    shuffle_write_time: Optional[StrictInt] = Field(default=None, alias="shuffleWriteTime")
    shuffle_write_records: Optional[StrictInt] = Field(default=None, alias="shuffleWriteRecords")
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    details: Optional[StrictStr] = None
    scheduling_pool: Optional[StrictStr] = Field(default=None, alias="schedulingPool")
    rdd_ids: Optional[List[StrictInt]] = Field(default=None, alias="rddIds")
    accumulator_updates: Optional[List[AccumulatorUpdate]] = Field(default=None, alias="accumulatorUpdates")
    tasks: Optional[Dict[str, Task]] = Field(default=None, description="Map of task ID to task data. Present when details=true.")
    executor_summary: Optional[Dict[str, ExecutorStageSummary]] = Field(default=None, description="Map of executor ID to executor stage summary.", alias="executorSummary")
    speculation_summary: Optional[SpeculationStageSummary] = Field(default=None, alias="speculationSummary")
    killed_tasks_summary: Optional[Dict[str, StrictInt]] = Field(default=None, alias="killedTasksSummary")
    resource_profile_id: Optional[StrictInt] = Field(default=None, alias="resourceProfileId")
    peak_executor_metrics: Optional[PeakMemoryMetrics] = Field(default=None, alias="peakExecutorMetrics")
    task_metrics_distributions: Optional[TaskMetricsSummary] = Field(default=None, alias="taskMetricsDistributions")
    executor_metrics_distributions: Optional[ExecutorMetricsDistributions] = Field(default=None, alias="executorMetricsDistributions")
    is_shuffle_push_enabled: Optional[StrictBool] = Field(default=None, alias="isShufflePushEnabled")
    shuffle_mergers_count: Optional[StrictInt] = Field(default=None, alias="shuffleMergersCount")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["status", "stageId", "attemptId", "numTasks", "numActiveTasks", "numCompleteTasks", "numFailedTasks", "numKilledTasks", "numCompletedIndices", "submissionTime", "firstTaskLaunchedTime", "completionTime", "failureReason", "executorDeserializeTime", "executorDeserializeCpuTime", "executorRunTime", "executorCpuTime", "resultSize", "jvmGcTime", "resultSerializationTime", "memoryBytesSpilled", "diskBytesSpilled", "peakExecutionMemory", "inputBytes", "inputRecords", "outputBytes", "outputRecords", "shuffleRemoteBlocksFetched", "shuffleLocalBlocksFetched", "shuffleFetchWaitTime", "shuffleRemoteBytesRead", "shuffleRemoteBytesReadToDisk", "shuffleLocalBytesRead", "shuffleReadBytes", "shuffleReadRecords", "shuffleCorruptMergedBlockChunks", "shuffleMergedFetchFallbackCount", "shuffleMergedRemoteBlocksFetched", "shuffleMergedLocalBlocksFetched", "shuffleMergedRemoteChunksFetched", "shuffleMergedLocalChunksFetched", "shuffleMergedRemoteBytesRead", "shuffleMergedLocalBytesRead", "shuffleRemoteReqsDuration", "shuffleMergedRemoteReqsDuration", "shuffleWriteBytes", "shuffleWriteTime", "shuffleWriteRecords", "name", "description", "details", "schedulingPool", "rddIds", "accumulatorUpdates", "tasks", "executorSummary", "speculationSummary", "killedTasksSummary", "resourceProfileId", "peakExecutorMetrics", "taskMetricsDistributions", "executorMetricsDistributions", "isShufflePushEnabled", "shuffleMergersCount"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ACTIVE', 'COMPLETE', 'PENDING', 'FAILED', 'SKIPPED']):
            raise ValueError("must be one of enum values ('ACTIVE', 'COMPLETE', 'PENDING', 'FAILED', 'SKIPPED')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StageData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in accumulator_updates (list)
        _items = []
        if self.accumulator_updates:
            for _item_accumulator_updates in self.accumulator_updates:
                if _item_accumulator_updates:
                    _items.append(_item_accumulator_updates.to_dict())
            _dict['accumulatorUpdates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in tasks (dict)
        _field_dict = {}
        if self.tasks:
            for _key_tasks in self.tasks:
                if self.tasks[_key_tasks]:
                    _field_dict[_key_tasks] = self.tasks[_key_tasks].to_dict()
            _dict['tasks'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in executor_summary (dict)
        _field_dict = {}
        if self.executor_summary:
            for _key_executor_summary in self.executor_summary:
                if self.executor_summary[_key_executor_summary]:
                    _field_dict[_key_executor_summary] = self.executor_summary[_key_executor_summary].to_dict()
            _dict['executorSummary'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of speculation_summary
        if self.speculation_summary:
            _dict['speculationSummary'] = self.speculation_summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of peak_executor_metrics
        if self.peak_executor_metrics:
            _dict['peakExecutorMetrics'] = self.peak_executor_metrics.to_dict()
        # override the default output from pydantic by calling `to_dict()` of task_metrics_distributions
        if self.task_metrics_distributions:
            _dict['taskMetricsDistributions'] = self.task_metrics_distributions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of executor_metrics_distributions
        if self.executor_metrics_distributions:
            _dict['executorMetricsDistributions'] = self.executor_metrics_distributions.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StageData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "stageId": obj.get("stageId"),
            "attemptId": obj.get("attemptId"),
            "numTasks": obj.get("numTasks"),
            "numActiveTasks": obj.get("numActiveTasks"),
            "numCompleteTasks": obj.get("numCompleteTasks"),
            "numFailedTasks": obj.get("numFailedTasks"),
            "numKilledTasks": obj.get("numKilledTasks"),
            "numCompletedIndices": obj.get("numCompletedIndices"),
            "submissionTime": obj.get("submissionTime"),
            "firstTaskLaunchedTime": obj.get("firstTaskLaunchedTime"),
            "completionTime": obj.get("completionTime"),
            "failureReason": obj.get("failureReason"),
            "executorDeserializeTime": obj.get("executorDeserializeTime"),
            "executorDeserializeCpuTime": obj.get("executorDeserializeCpuTime"),
            "executorRunTime": obj.get("executorRunTime"),
            "executorCpuTime": obj.get("executorCpuTime"),
            "resultSize": obj.get("resultSize"),
            "jvmGcTime": obj.get("jvmGcTime"),
            "resultSerializationTime": obj.get("resultSerializationTime"),
            "memoryBytesSpilled": obj.get("memoryBytesSpilled"),
            "diskBytesSpilled": obj.get("diskBytesSpilled"),
            "peakExecutionMemory": obj.get("peakExecutionMemory"),
            "inputBytes": obj.get("inputBytes"),
            "inputRecords": obj.get("inputRecords"),
            "outputBytes": obj.get("outputBytes"),
            "outputRecords": obj.get("outputRecords"),
            "shuffleRemoteBlocksFetched": obj.get("shuffleRemoteBlocksFetched"),
            "shuffleLocalBlocksFetched": obj.get("shuffleLocalBlocksFetched"),
            "shuffleFetchWaitTime": obj.get("shuffleFetchWaitTime"),
            "shuffleRemoteBytesRead": obj.get("shuffleRemoteBytesRead"),
            "shuffleRemoteBytesReadToDisk": obj.get("shuffleRemoteBytesReadToDisk"),
            "shuffleLocalBytesRead": obj.get("shuffleLocalBytesRead"),
            "shuffleReadBytes": obj.get("shuffleReadBytes"),
            "shuffleReadRecords": obj.get("shuffleReadRecords"),
            "shuffleCorruptMergedBlockChunks": obj.get("shuffleCorruptMergedBlockChunks"),
            "shuffleMergedFetchFallbackCount": obj.get("shuffleMergedFetchFallbackCount"),
            "shuffleMergedRemoteBlocksFetched": obj.get("shuffleMergedRemoteBlocksFetched"),
            "shuffleMergedLocalBlocksFetched": obj.get("shuffleMergedLocalBlocksFetched"),
            "shuffleMergedRemoteChunksFetched": obj.get("shuffleMergedRemoteChunksFetched"),
            "shuffleMergedLocalChunksFetched": obj.get("shuffleMergedLocalChunksFetched"),
            "shuffleMergedRemoteBytesRead": obj.get("shuffleMergedRemoteBytesRead"),
            "shuffleMergedLocalBytesRead": obj.get("shuffleMergedLocalBytesRead"),
            "shuffleRemoteReqsDuration": obj.get("shuffleRemoteReqsDuration"),
            "shuffleMergedRemoteReqsDuration": obj.get("shuffleMergedRemoteReqsDuration"),
            "shuffleWriteBytes": obj.get("shuffleWriteBytes"),
            "shuffleWriteTime": obj.get("shuffleWriteTime"),
            "shuffleWriteRecords": obj.get("shuffleWriteRecords"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "details": obj.get("details"),
            "schedulingPool": obj.get("schedulingPool"),
            "rddIds": obj.get("rddIds"),
            "accumulatorUpdates": [AccumulatorUpdate.from_dict(_item) for _item in obj["accumulatorUpdates"]] if obj.get("accumulatorUpdates") is not None else None,
            "tasks": dict(
                (_k, Task.from_dict(_v))
                for _k, _v in obj["tasks"].items()
            )
            if obj.get("tasks") is not None
            else None,
            "executorSummary": dict(
                (_k, ExecutorStageSummary.from_dict(_v))
                for _k, _v in obj["executorSummary"].items()
            )
            if obj.get("executorSummary") is not None
            else None,
            "speculationSummary": SpeculationStageSummary.from_dict(obj["speculationSummary"]) if obj.get("speculationSummary") is not None else None,
            "killedTasksSummary": obj.get("killedTasksSummary"),
            "resourceProfileId": obj.get("resourceProfileId"),
            "peakExecutorMetrics": PeakMemoryMetrics.from_dict(obj["peakExecutorMetrics"]) if obj.get("peakExecutorMetrics") is not None else None,
            "taskMetricsDistributions": TaskMetricsSummary.from_dict(obj["taskMetricsDistributions"]) if obj.get("taskMetricsDistributions") is not None else None,
            "executorMetricsDistributions": ExecutorMetricsDistributions.from_dict(obj["executorMetricsDistributions"]) if obj.get("executorMetricsDistributions") is not None else None,
            "isShufflePushEnabled": obj.get("isShufflePushEnabled"),
            "shuffleMergersCount": obj.get("shuffleMergersCount")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


