# coding: utf-8

"""
    Apache Spark History Server REST API

    REST API for the Apache Spark History Server, providing access to application history, jobs, stages, executors, storage, SQL, streaming, and environment information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StreamingStatistics(BaseModel):
    """
    StreamingStatistics
    """ # noqa: E501
    start_time: Optional[StrictStr] = Field(default=None, alias="startTime")
    batch_duration: Optional[StrictInt] = Field(default=None, alias="batchDuration")
    num_receivers: Optional[StrictInt] = Field(default=None, alias="numReceivers")
    num_active_receivers: Optional[StrictInt] = Field(default=None, alias="numActiveReceivers")
    num_inactive_receivers: Optional[StrictInt] = Field(default=None, alias="numInactiveReceivers")
    num_total_completed_batches: Optional[StrictInt] = Field(default=None, alias="numTotalCompletedBatches")
    num_retained_completed_batches: Optional[StrictInt] = Field(default=None, alias="numRetainedCompletedBatches")
    num_active_batches: Optional[StrictInt] = Field(default=None, alias="numActiveBatches")
    num_processed_records: Optional[StrictInt] = Field(default=None, alias="numProcessedRecords")
    num_received_records: Optional[StrictInt] = Field(default=None, alias="numReceivedRecords")
    avg_input_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="avgInputRate")
    avg_scheduling_delay: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="avgSchedulingDelay")
    avg_processing_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="avgProcessingTime")
    avg_total_delay: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="avgTotalDelay")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["startTime", "batchDuration", "numReceivers", "numActiveReceivers", "numInactiveReceivers", "numTotalCompletedBatches", "numRetainedCompletedBatches", "numActiveBatches", "numProcessedRecords", "numReceivedRecords", "avgInputRate", "avgSchedulingDelay", "avgProcessingTime", "avgTotalDelay"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StreamingStatistics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StreamingStatistics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "startTime": obj.get("startTime"),
            "batchDuration": obj.get("batchDuration"),
            "numReceivers": obj.get("numReceivers"),
            "numActiveReceivers": obj.get("numActiveReceivers"),
            "numInactiveReceivers": obj.get("numInactiveReceivers"),
            "numTotalCompletedBatches": obj.get("numTotalCompletedBatches"),
            "numRetainedCompletedBatches": obj.get("numRetainedCompletedBatches"),
            "numActiveBatches": obj.get("numActiveBatches"),
            "numProcessedRecords": obj.get("numProcessedRecords"),
            "numReceivedRecords": obj.get("numReceivedRecords"),
            "avgInputRate": obj.get("avgInputRate"),
            "avgSchedulingDelay": obj.get("avgSchedulingDelay"),
            "avgProcessingTime": obj.get("avgProcessingTime"),
            "avgTotalDelay": obj.get("avgTotalDelay")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


