# coding: utf-8

"""
    Apache Spark History Server REST API

    REST API for the Apache Spark History Server, providing access to application history, jobs, stages, executors, storage, SQL, streaming, and environment information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StreamingBatch(BaseModel):
    """
    StreamingBatch
    """ # noqa: E501
    batch_id: Optional[StrictInt] = Field(default=None, alias="batchId")
    batch_time: Optional[StrictStr] = Field(default=None, alias="batchTime")
    status: Optional[StrictStr] = None
    batch_duration: Optional[StrictInt] = Field(default=None, alias="batchDuration")
    input_size: Optional[StrictInt] = Field(default=None, alias="inputSize")
    scheduling_delay: Optional[StrictInt] = Field(default=None, alias="schedulingDelay")
    processing_time: Optional[StrictInt] = Field(default=None, alias="processingTime")
    total_delay: Optional[StrictInt] = Field(default=None, alias="totalDelay")
    num_active_output_ops: Optional[StrictInt] = Field(default=None, alias="numActiveOutputOps")
    num_completed_output_ops: Optional[StrictInt] = Field(default=None, alias="numCompletedOutputOps")
    num_failed_output_ops: Optional[StrictInt] = Field(default=None, alias="numFailedOutputOps")
    num_total_output_ops: Optional[StrictInt] = Field(default=None, alias="numTotalOutputOps")
    first_failure_reason: Optional[StrictStr] = Field(default=None, alias="firstFailureReason")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["batchId", "batchTime", "status", "batchDuration", "inputSize", "schedulingDelay", "processingTime", "totalDelay", "numActiveOutputOps", "numCompletedOutputOps", "numFailedOutputOps", "numTotalOutputOps", "firstFailureReason"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StreamingBatch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if scheduling_delay (nullable) is None
        # and model_fields_set contains the field
        if self.scheduling_delay is None and "scheduling_delay" in self.model_fields_set:
            _dict['schedulingDelay'] = None

        # set to None if processing_time (nullable) is None
        # and model_fields_set contains the field
        if self.processing_time is None and "processing_time" in self.model_fields_set:
            _dict['processingTime'] = None

        # set to None if total_delay (nullable) is None
        # and model_fields_set contains the field
        if self.total_delay is None and "total_delay" in self.model_fields_set:
            _dict['totalDelay'] = None

        # set to None if first_failure_reason (nullable) is None
        # and model_fields_set contains the field
        if self.first_failure_reason is None and "first_failure_reason" in self.model_fields_set:
            _dict['firstFailureReason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StreamingBatch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "batchId": obj.get("batchId"),
            "batchTime": obj.get("batchTime"),
            "status": obj.get("status"),
            "batchDuration": obj.get("batchDuration"),
            "inputSize": obj.get("inputSize"),
            "schedulingDelay": obj.get("schedulingDelay"),
            "processingTime": obj.get("processingTime"),
            "totalDelay": obj.get("totalDelay"),
            "numActiveOutputOps": obj.get("numActiveOutputOps"),
            "numCompletedOutputOps": obj.get("numCompletedOutputOps"),
            "numFailedOutputOps": obj.get("numFailedOutputOps"),
            "numTotalOutputOps": obj.get("numTotalOutputOps"),
            "firstFailureReason": obj.get("firstFailureReason")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


