# coding: utf-8

"""
    Apache Spark History Server REST API

    REST API for the Apache Spark History Server, providing access to application history, jobs, stages, executors, storage, SQL, streaming, and environment information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from spark_history_mcp.api_client.models.task_metrics_summary_input_metrics import TaskMetricsSummaryInputMetrics
from spark_history_mcp.api_client.models.task_metrics_summary_output_metrics import TaskMetricsSummaryOutputMetrics
from spark_history_mcp.api_client.models.task_metrics_summary_shuffle_read_metrics import TaskMetricsSummaryShuffleReadMetrics
from spark_history_mcp.api_client.models.task_metrics_summary_shuffle_write_metrics import TaskMetricsSummaryShuffleWriteMetrics
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TaskMetricsSummary(BaseModel):
    """
    Each metric field contains an array of values corresponding to the requested quantiles.
    """ # noqa: E501
    quantiles: Optional[List[Union[StrictFloat, StrictInt]]] = None
    duration: Optional[List[Union[StrictFloat, StrictInt]]] = None
    executor_deserialize_time: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="executorDeserializeTime")
    executor_deserialize_cpu_time: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="executorDeserializeCpuTime")
    executor_run_time: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="executorRunTime")
    executor_cpu_time: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="executorCpuTime")
    result_size: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="resultSize")
    jvm_gc_time: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="jvmGcTime")
    result_serialization_time: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="resultSerializationTime")
    getting_result_time: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="gettingResultTime")
    scheduler_delay: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="schedulerDelay")
    peak_execution_memory: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="peakExecutionMemory")
    memory_bytes_spilled: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="memoryBytesSpilled")
    disk_bytes_spilled: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, alias="diskBytesSpilled")
    input_metrics: Optional[TaskMetricsSummaryInputMetrics] = Field(default=None, alias="inputMetrics")
    output_metrics: Optional[TaskMetricsSummaryOutputMetrics] = Field(default=None, alias="outputMetrics")
    shuffle_read_metrics: Optional[TaskMetricsSummaryShuffleReadMetrics] = Field(default=None, alias="shuffleReadMetrics")
    shuffle_write_metrics: Optional[TaskMetricsSummaryShuffleWriteMetrics] = Field(default=None, alias="shuffleWriteMetrics")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["quantiles", "duration", "executorDeserializeTime", "executorDeserializeCpuTime", "executorRunTime", "executorCpuTime", "resultSize", "jvmGcTime", "resultSerializationTime", "gettingResultTime", "schedulerDelay", "peakExecutionMemory", "memoryBytesSpilled", "diskBytesSpilled", "inputMetrics", "outputMetrics", "shuffleReadMetrics", "shuffleWriteMetrics"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TaskMetricsSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of input_metrics
        if self.input_metrics:
            _dict['inputMetrics'] = self.input_metrics.to_dict()
        # override the default output from pydantic by calling `to_dict()` of output_metrics
        if self.output_metrics:
            _dict['outputMetrics'] = self.output_metrics.to_dict()
        # override the default output from pydantic by calling `to_dict()` of shuffle_read_metrics
        if self.shuffle_read_metrics:
            _dict['shuffleReadMetrics'] = self.shuffle_read_metrics.to_dict()
        # override the default output from pydantic by calling `to_dict()` of shuffle_write_metrics
        if self.shuffle_write_metrics:
            _dict['shuffleWriteMetrics'] = self.shuffle_write_metrics.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TaskMetricsSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "quantiles": obj.get("quantiles"),
            "duration": obj.get("duration"),
            "executorDeserializeTime": obj.get("executorDeserializeTime"),
            "executorDeserializeCpuTime": obj.get("executorDeserializeCpuTime"),
            "executorRunTime": obj.get("executorRunTime"),
            "executorCpuTime": obj.get("executorCpuTime"),
            "resultSize": obj.get("resultSize"),
            "jvmGcTime": obj.get("jvmGcTime"),
            "resultSerializationTime": obj.get("resultSerializationTime"),
            "gettingResultTime": obj.get("gettingResultTime"),
            "schedulerDelay": obj.get("schedulerDelay"),
            "peakExecutionMemory": obj.get("peakExecutionMemory"),
            "memoryBytesSpilled": obj.get("memoryBytesSpilled"),
            "diskBytesSpilled": obj.get("diskBytesSpilled"),
            "inputMetrics": TaskMetricsSummaryInputMetrics.from_dict(obj["inputMetrics"]) if obj.get("inputMetrics") is not None else None,
            "outputMetrics": TaskMetricsSummaryOutputMetrics.from_dict(obj["outputMetrics"]) if obj.get("outputMetrics") is not None else None,
            "shuffleReadMetrics": TaskMetricsSummaryShuffleReadMetrics.from_dict(obj["shuffleReadMetrics"]) if obj.get("shuffleReadMetrics") is not None else None,
            "shuffleWriteMetrics": TaskMetricsSummaryShuffleWriteMetrics.from_dict(obj["shuffleWriteMetrics"]) if obj.get("shuffleWriteMetrics") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


