# coding: utf-8

"""
    Apache Spark History Server REST API

    REST API for the Apache Spark History Server, providing access to application history, jobs, stages, executors, storage, SQL, streaming, and environment information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from spark_history_mcp.api_client.models.accumulator_update import AccumulatorUpdate
from spark_history_mcp.api_client.models.task_metrics import TaskMetrics
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Task(BaseModel):
    """
    Task
    """ # noqa: E501
    task_id: Optional[StrictInt] = Field(default=None, alias="taskId")
    index: Optional[StrictInt] = None
    attempt: Optional[StrictInt] = None
    partition_id: Optional[StrictInt] = Field(default=None, alias="partitionId")
    launch_time: Optional[StrictStr] = Field(default=None, alias="launchTime")
    result_fetch_start: Optional[StrictStr] = Field(default=None, alias="resultFetchStart")
    duration: Optional[StrictInt] = None
    executor_id: Optional[StrictStr] = Field(default=None, alias="executorId")
    host: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    task_locality: Optional[StrictStr] = Field(default=None, alias="taskLocality")
    speculative: Optional[StrictBool] = None
    accumulator_updates: Optional[List[AccumulatorUpdate]] = Field(default=None, alias="accumulatorUpdates")
    error_message: Optional[StrictStr] = Field(default=None, alias="errorMessage")
    task_metrics: Optional[TaskMetrics] = Field(default=None, alias="taskMetrics")
    executor_logs: Optional[Dict[str, StrictStr]] = Field(default=None, alias="executorLogs")
    scheduler_delay: Optional[StrictInt] = Field(default=None, alias="schedulerDelay")
    getting_result_time: Optional[StrictInt] = Field(default=None, alias="gettingResultTime")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["taskId", "index", "attempt", "partitionId", "launchTime", "resultFetchStart", "duration", "executorId", "host", "status", "taskLocality", "speculative", "accumulatorUpdates", "errorMessage", "taskMetrics", "executorLogs", "schedulerDelay", "gettingResultTime"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Task from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in accumulator_updates (list)
        _items = []
        if self.accumulator_updates:
            for _item_accumulator_updates in self.accumulator_updates:
                if _item_accumulator_updates:
                    _items.append(_item_accumulator_updates.to_dict())
            _dict['accumulatorUpdates'] = _items
        # override the default output from pydantic by calling `to_dict()` of task_metrics
        if self.task_metrics:
            _dict['taskMetrics'] = self.task_metrics.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Task from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "taskId": obj.get("taskId"),
            "index": obj.get("index"),
            "attempt": obj.get("attempt"),
            "partitionId": obj.get("partitionId"),
            "launchTime": obj.get("launchTime"),
            "resultFetchStart": obj.get("resultFetchStart"),
            "duration": obj.get("duration"),
            "executorId": obj.get("executorId"),
            "host": obj.get("host"),
            "status": obj.get("status"),
            "taskLocality": obj.get("taskLocality"),
            "speculative": obj.get("speculative"),
            "accumulatorUpdates": [AccumulatorUpdate.from_dict(_item) for _item in obj["accumulatorUpdates"]] if obj.get("accumulatorUpdates") is not None else None,
            "errorMessage": obj.get("errorMessage"),
            "taskMetrics": TaskMetrics.from_dict(obj["taskMetrics"]) if obj.get("taskMetrics") is not None else None,
            "executorLogs": obj.get("executorLogs"),
            "schedulerDelay": obj.get("schedulerDelay"),
            "gettingResultTime": obj.get("gettingResultTime")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


