# coding: utf-8

"""
    Apache Spark History Server REST API

    REST API for the Apache Spark History Server, providing access to application history, jobs, stages, executors, storage, SQL, streaming, and environment information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from spark_history_mcp.api_client.models.thread_stack_trace_stack_trace import ThreadStackTraceStackTrace
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ThreadStackTrace(BaseModel):
    """
    ThreadStackTrace
    """ # noqa: E501
    thread_id: Optional[StrictInt] = Field(default=None, alias="threadId")
    thread_name: Optional[StrictStr] = Field(default=None, alias="threadName")
    thread_state: Optional[StrictStr] = Field(default=None, alias="threadState")
    stack_trace: Optional[ThreadStackTraceStackTrace] = Field(default=None, alias="stackTrace")
    blocked_by_thread_id: Optional[StrictInt] = Field(default=None, alias="blockedByThreadId")
    blocked_by_lock: Optional[StrictStr] = Field(default=None, alias="blockedByLock")
    holding_locks: Optional[List[StrictStr]] = Field(default=None, alias="holdingLocks")
    synchronizers: Optional[List[StrictStr]] = None
    monitors: Optional[List[StrictStr]] = None
    lock_name: Optional[StrictStr] = Field(default=None, alias="lockName")
    lock_owner_name: Optional[StrictStr] = Field(default=None, alias="lockOwnerName")
    suspended: Optional[StrictBool] = None
    in_native: Optional[StrictBool] = Field(default=None, alias="inNative")
    is_daemon: Optional[StrictBool] = Field(default=None, alias="isDaemon")
    priority: Optional[StrictInt] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["threadId", "threadName", "threadState", "stackTrace", "blockedByThreadId", "blockedByLock", "holdingLocks", "synchronizers", "monitors", "lockName", "lockOwnerName", "suspended", "inNative", "isDaemon", "priority"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ThreadStackTrace from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of stack_trace
        if self.stack_trace:
            _dict['stackTrace'] = self.stack_trace.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if blocked_by_thread_id (nullable) is None
        # and model_fields_set contains the field
        if self.blocked_by_thread_id is None and "blocked_by_thread_id" in self.model_fields_set:
            _dict['blockedByThreadId'] = None

        # set to None if lock_name (nullable) is None
        # and model_fields_set contains the field
        if self.lock_name is None and "lock_name" in self.model_fields_set:
            _dict['lockName'] = None

        # set to None if lock_owner_name (nullable) is None
        # and model_fields_set contains the field
        if self.lock_owner_name is None and "lock_owner_name" in self.model_fields_set:
            _dict['lockOwnerName'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ThreadStackTrace from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "threadId": obj.get("threadId"),
            "threadName": obj.get("threadName"),
            "threadState": obj.get("threadState"),
            "stackTrace": ThreadStackTraceStackTrace.from_dict(obj["stackTrace"]) if obj.get("stackTrace") is not None else None,
            "blockedByThreadId": obj.get("blockedByThreadId"),
            "blockedByLock": obj.get("blockedByLock"),
            "holdingLocks": obj.get("holdingLocks"),
            "synchronizers": obj.get("synchronizers"),
            "monitors": obj.get("monitors"),
            "lockName": obj.get("lockName"),
            "lockOwnerName": obj.get("lockOwnerName"),
            "suspended": obj.get("suspended"),
            "inNative": obj.get("inNative"),
            "isDaemon": obj.get("isDaemon"),
            "priority": obj.get("priority")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


